id = "dockerignore"
name = "Docker Ignore"
version = "0.1.0"
schema_version = 1
authors = ["eth0net <eth0net@pm.me>"]
description = "Syntax highlighting for .dockerignore files"
repository = "https://github.com/eth0net/zed-dockerignore"

[grammars.gitignore]
repository = "https://github.com/shunsambongi/tree-sitter-gitignore"
commit = "f4685bf11ac466dd278449bcfe5fd014e94aa504"
